# User specific aliases and functions
alias ll='/bin/ls -FCal --color=tty'
alias ls='/bin/ls -FC --color=tty'

# User specific environment and startup programs
export PATH=$PATH:$HOME/bin
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export LC_COLLATE=en_US.UTF-8
export LC_TIME=en_US.UTF-8
export LC_NUMERIC=en_US.UTF-8
export LC_MONETARY=en_US.UTF-8
export LC_MESSAGES=en_US.UTF-8

export PS1='\h \w$ '
export EDITOR="/usr/bin/vim"
#export VISUAL="/usr/bin/less"
export LS_COLORS="di=32:bd=37:cd=37"
